---
- hosts: web-servers
  become: true
  tasks:
    - name: copy war onto tomcat server
      copy:
        src: /opt/playbooks/hello-world/webapp/target/webapp.war
        dest: /opt/tomcat/latest/webapps
